### ISSUE TITLE
Notification Adjustments

### ISSUE THREAD

**Issue by H-Ashcraft** [v4lpt/TPC#1]
I love your app! The pie chart style display is the best I've seen. I love how the notification sound plays through my earbuds. 

I was wondering if if would be possible to add a vibrate notification that alerts at the same time as the sound notification. This would make it so I could use this app at work without my earbuds in. I can't have the notification sound going off at work without my earbuds. 

I was also wondering if it would be possible to change the notification sound to something that plays for a shorter time. I love the bell sound that is currently used, but it would be nice if it was shorter. 

Anyways, I understand this app is free and you are being nice to share it. I would love to see the features I mentioned added, but I totally understand if they aren't. Thanks!

**Comment by v4lpt** [comment]
🤩😃👍
Glad you like it. 
Will def add your suggestions. 
It's on the list. 
Think early December (lots of projects) 

Cheers :)

**Comment by v4lpt** [comment]
![image](https://github.com/user-attachments/assets/8f0edb9c-9bb4-41da-a2d5-ee7dc235dcef)
newest release has the ability to toggle vibration and sounds :) 

https://github.com/v4lpt/TPC/releases/tag/v1.0.2
