### ISSUE TITLE
release v1.0.2 lacks APKs

### ISSUE THREAD

**Issue by IzzySoft** [v4lpt/TPC#3]
There are no APKs attached to the currently latest release (v1.0.2), could you please add them? Otherwise that release won't reach IzzyOnDroid, and the RB verification builders have nothing to prove it's reproducible :wink:

Thanks!

**Comment by v4lpt** [comment]
i updated the release. 
:)

**Comment by IzzySoft** [comment]
Thanks! Was pulled in fine (including RB) while I was AFK for the holidays :stuck_out_tongue_winking_eye:
